# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

# Spark properties
spark.master                     spark://localhost:7077
spark.eventLog.enabled           true
spark.eventLog.dir               /tmp/spark-events
spark.history.fs.logDirectory    /tmp/spark-events

# Logging
spark.driver.memory              4g
spark.executor.memory            4g
spark.executor.cores             2
