#!/bin/bash
# Generate overlay kustomization.yaml files from template
# This DRYs out the duplication by generating from a single source

set -e

# Define versions to generate
declare -A VERSIONS=(
    ["3.5.7"]="0.8.0"
    ["2.4.8"]="0.7.1"
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERLAYS_DIR="$SCRIPT_DIR/k8s/overlays"

generate_kustomization() {
    local spark_version=$1
    local livy_version=$2
    local overlay_dir="$OVERLAYS_DIR/spark-$spark_version"
    local is_default=$3
    
    mkdir -p "$overlay_dir"
    
    cat > "$overlay_dir/kustomization.yaml" << EOF
# ⚠️  AUTO-GENERATED FILE
# This file is generated by scripts/generate-overlays.sh
# DO NOT EDIT DIRECTLY - use the script to regenerate all overlays
# To add a new version or modify: edit scripts/generate-overlays.sh and run it

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay for Spark $spark_version + Livy $livy_version
$(if [ "$is_default" = "1" ]; then echo "# Recommended for production with full PySpark support"; else echo "# Note: PySpark has known compatibility issues with Python 3.10+"; echo "# Scala sessions work perfectly. For PySpark, use spark-3.5.7 overlay instead."; fi)
# Usage: kubectl apply -k k8s/overlays/spark-$spark_version/

resources:
  - ../../base

# Override image tags
images:
  - name: stedoh/spark-livy
    newTag: "$spark_version"

# Patch ConfigMap pod templates with $spark_version images
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: spark-driver-pod-template
    patch: |-
      - op: replace
        path: /data/driver-pod-template.yaml
        value: |
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - name: spark-driver
              image: stedoh/spark-livy:$spark_version
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 1000m
                  memory: 2Gi
                limits:
                  cpu: 2000m
                  memory: 4Gi
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
              - name: spark-events
                mountPath: /tmp/spark-events
              volumes:
              - name: spark-events
                emptyDir: {}
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: spark-executor-pod-template
    patch: |-
      - op: replace
        path: /data/executor-pod-template.yaml
        value: |
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - name: spark-executor
              image: stedoh/spark-livy:$spark_version
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 1000m
                  memory: 2Gi
                limits:
                  cpu: 2000m
                  memory: 4Gi
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
              - name: spark-events
                mountPath: /tmp/spark-events
              volumes:
              - name: spark-events
                emptyDir: {}

# Add version labels (to pods only, not to selector - selector is immutable)
labels:
  - includeSelectors: false
    pairs:
      spark-version: "$spark_version"
      livy-version: "$livy_version"
EOF

    echo "✅ Generated: $overlay_dir/kustomization.yaml"
}

echo "Generating Kustomize overlay files from template..."
echo ""

# Generate all versions
for spark_ver in "${!VERSIONS[@]}"; do
    livy_ver="${VERSIONS[$spark_ver]}"
    is_default=$([[ "$spark_ver" == "3.5.7" ]] && echo "1" || echo "0")
    generate_kustomization "$spark_ver" "$livy_ver" "$is_default"
done

echo ""
echo "All overlay kustomization files generated successfully!"
